#!/bin/sh -e

libdir="/home/sf-bb/docker/apt/packages/nghttp2/lib"
if [ -d "$libdir/.libs" ]; then
    libdir="$libdir/.libs"
fi

export CGO_CFLAGS="-I/home/sf-bb/docker/apt/packages/nghttp2/lib/includes -I/home/sf-bb/docker/apt/packages/nghttp2/lib/includes"
export CGO_LDFLAGS="-L$libdir"
export LD_LIBRARY_PATH="$libdir"
export GODEBUG=cgocheck=0
"$@"
